#!/usr/bin/env python3
"""Which client data a run would use (ADR-0021), for the launchers and for people.

    python tools/datasources/run.py check [--bat FILE] [--sh FILE] [--quiet]
    python tools/datasources/run.py gen-cs [--check]

Resolves the ADR-0021 order: a custom data folder (UO_CUSTOM_DATA), then the
UO install (UO_CLIENT_DATA from the environment, else config.local.bat or the
central config, else the platform default), then the first-run wizard.
It prints what was chosen and every candidate that was passed over, and why.

--bat FILE writes a batch fragment a launcher `call`s, which sets
UO_CLIENT_DATA to the chosen install and, for a layered custom folder,
UO_FILES_OVERRIDE to an override file written under build/datasources/.
--sh FILE writes the same as shell exports, for the .sh launchers.

gen-cs writes godot/GUO/src/Bootstrap/DataRequirements.g.cs, the runtime's copy
of the required set in tools/guo/formats.py, so the client and the tools judge
a folder the same way (ADR-0021). --check only compares, exit 1 if stale;
tools/guo/test_config.py runs it in CI.

Exit 0: valid data. Exit 3: no valid data -- run the first-run wizard (the
client opens it; nothing here is an error). Reads only, apart from build/.
"""
from __future__ import annotations

import argparse
import shlex
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from guo import load_config  # noqa: E402
from guo.datasources import WIZARD_EXIT, resolve_config, write_override  # noqa: E402
from guo.formats import required_files  # noqa: E402

GENERATED = Path("godot") / "GUO" / "src" / "Bootstrap" / "DataRequirements.g.cs"


def generated_cs() -> str:
    """The C# table of required entries, from formats.py."""
    def arr(names) -> str:
        return "new[] { " + ", ".join(f'"{n}"' for n in names) + " }" if names else "System.Array.Empty<string>()"

    rows = [f'        new("{f.key}", {arr(f.mul)}, {arr(f.uop)}, {arr(f.indexed_by)}),' for f in required_files()]
    return "\n".join([
        "// <auto-generated>",
        "// Generated by tools/datasources/run.py gen-cs from tools/guo/formats.py.",
        "// Do not edit: change formats.py and regenerate. CI checks it is current.",
        "// </auto-generated>",
        "namespace GUO.Host;",
        "",
        "/// <summary>The required client data entries (ADR-0021 validity rule).</summary>",
        "internal static class DataRequirements",
        "{",
        "    internal sealed record Entry(string Key, string[] Mul, string[] Uop, string[] Index);",
        "",
        "    internal static readonly Entry[] Required =",
        "    {",
        *rows,
        "    };",
        "}",
        "",
    ])


def gen_cs(check: bool) -> int:
    path = load_config().root / GENERATED
    want = generated_cs()
    have = path.read_text(encoding="utf-8") if path.exists() else ""
    if check:
        ok = have.replace("\r\n", "\n") == want
        print(f"[datasources] {GENERATED}: {'current' if ok else 'STALE, run gen-cs'}")
        return 0 if ok else 1
    path.write_text(want, encoding="utf-8", newline="\n")
    print(f"[datasources] wrote {GENERATED} ({len(required_files())} required entries)")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("command", choices=["check", "gen-cs"])
    ap.add_argument("--bat", type=Path, help="write set lines for a launcher to call")
    ap.add_argument("--sh", type=Path, help="write export lines for a .sh launcher to source")
    ap.add_argument("--quiet", action="store_true", help="only the verdict line")
    ap.add_argument("--check", action="store_true", help="gen-cs: compare only")
    args = ap.parse_args()
    if args.command == "gen-cs":
        return gen_cs(args.check)
    cfg = load_config()
    res = resolve_config(cfg)

    override = write_override(res, cfg.build / "datasources" / "files_override.txt")
    print(f"[datasources] {res.message()}")
    if not args.quiet:
        for note in res.notes:
            print(f"[datasources]   passed over: {note}")
        if override:
            print(f"[datasources]   {len(res.overrides)} file(s) layered through {override}")

    if args.bat:
        lines = ["@echo off"]
        if res.ok:
            lines.append(f'set "UO_CLIENT_DATA={res.client_data}"')
        lines.append(f'set "UO_FILES_OVERRIDE={override or ""}"')
        lines.append(f'set "UO_DATA_SOURCE={res.source}"')
        args.bat.parent.mkdir(parents=True, exist_ok=True)
        args.bat.write_text("\r\n".join(lines) + "\r\n", encoding="utf-8")
    if args.sh:
        values = {}
        if res.ok:
            values["UO_CLIENT_DATA"] = str(res.client_data)
        values["UO_FILES_OVERRIDE"] = str(override or "")
        values["UO_DATA_SOURCE"] = res.source
        args.sh.parent.mkdir(parents=True, exist_ok=True)
        args.sh.write_text("".join(f"export {k}={shlex.quote(v)}\n" for k, v in values.items()), encoding="utf-8")
    return 0 if res.ok else WIZARD_EXIT


if __name__ == "__main__":
    sys.exit(main())
